### ISSUE TITLE
ffmpeg6 does not exit normally when h264_nvmpi decoder used

### ISSUE THREAD

**Issue by alexp2021** [Keylost/jetson-ffmpeg#1]
It compiled and works with ffmpeg6. Thanks a lot!
There is one minor issue I noticed:
Everything works fine when h264_nvmpi used for encoding only.
But when using it for both encoding and decoding, ffmpeg does not exit normally after finish transcoding. It stucks and only 3 times Ctrl+C helps.

**Comment by Keylost** [comment]
Thanks for the report. Fixed. Rebuild the library from the master branch. FFmpeg does not need to be rebuilt

**Comment by alexp2021** [comment]
Now it works for both encoding and decoding.
Thank you!
