### ISSUE TITLE
Cannot found LIB_NVBUF?

### ISSUE THREAD

**Issue by Washington-DC** [Keylost/jetson-ffmpeg#16]
Logs:

`
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIB_NVBUF
    linked by target "nvmpi" in directory /home/tyiot/jetpack-ffmepg/jetson-ffmpeg
`

I am using Agx Orin, Jetpack version 5.1.2，When I was compiling, I encountered this issue。

**Comment by Washington-DC** [comment]
In Jetpack 5.1, the interface has changed. How should I modify it？

**Comment by Keylost** [comment]
This library supports the new API. 
The nvbuf_utils library was present in versions of jetpack before 5.1.2, but was completely removed in this version. This library is no longer needed for the build. Just comment out the find_library(LIB_NVBUF nvbuf_utils PATHS /usr/lib/aarch64-linux-gnu/tegra) line in CMakeLists.txt and it should work :)
I'll update the master branch a little later.

**Comment by pavloshargan** [comment]
> This library supports the new API. The nvbuf_utils library was present in versions of jetpack before 5.1.2, but was completely removed in this version. This library is no longer needed for the build. Just comment out the find_library(LIB_NVBUF nvbuf_utils PATHS /usr/lib/aarch64-linux-gnu/tegra) line in CMakeLists.txt and it should work :) I'll update the master branch a little later.

Awesome, thank you. Finally my journey of running hw encoding on jetson orin AGX with ffmpeg has ended on this single comment! Finally

**Comment by YCG1** [comment]
> 知道了。谢谢 ![image](https://private-user-images.githubusercontent.com/12068390/277637174-33a536cc-93ea-4222-ac0b-cc42d0967867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjUxNDEsIm5iZiI6MTcwNjc2NDg0MSwicGF0aCI6Ii8xMjA2ODM5MC8yNzc2MzcxNzQtMzNhNTM2Y2MtOTNlYS00MjIyLWFjMGItY2M0MmQwOTY3ODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA1MjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNzFlNTA4MjYyYmIxMTU0MmNkNzFkNWRmNWU1YjA0YjlmZmMxNjFlM2M4M2EzNjM3MTJhYTZkNzkxMGZlYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dasY2mMsiUBxr5JKA5-SQA-ioBUigIXF1Cvx6hMdtlM)

你好 很想知道您是怎么编译成功的 使用的ffmpeg的版本是多少呢？

**Comment by WangFengtu1996** [comment]
> This library supports the new API. The nvbuf_utils library was present in versions of jetpack before 5.1.2, but was completely removed in this version. This library is no longer needed for the build. Just comment out the find_library(LIB_NVBUF nvbuf_utils PATHS /usr/lib/aarch64-linux-gnu/tegra) line in CMakeLists.txt and it should work :) I'll update the master branch a little later.

thkx

**Comment by fingul** [comment]
in a one line. (jetpack 5.1+)

```
sed -i '/find_library(LIB_NVBUF nvbuf_utils PATHS \/usr\/lib\/aarch64-linux-gnu\/tegra)/s/^/#/' CMakeLists.txt
```

**Comment by Keylost** [comment]
Fixed it :)
