### ISSUE TITLE
Is there any sample for nvmpi without ffmpeg?

### ISSUE THREAD

**Issue by Kevin4ch** [Keylost/jetson-ffmpeg#17]

**Comment by bmegli** [comment]
There are two possible contexts to understand this question:

# Nvidia Multimedia API (NVMPI)

jetson-ffmpeg really uses this Nvidia Jetson API

See examples by NVIDIA here:
- https://docs.nvidia.com/jetson/l4t-multimedia/group__l4t__mm__test__group.html

I will prepare you. The examples are much worse than you might expect ;-)

I would advise against using NVMPI directly:
- you tie your code to Jetson only
- you learn Jetson only technology

# jetson-ffmpeg NVMPI library

This is thin wrapper on Nvidia Multimedia API (NVMPI) to enable integration with FFmpeg.

FFmpeg use in jetson_ffmpeg is kind of example use.

I would advise against using this layer directly:
- I don't think this interface was ever meant to be stable (not changing)
- you tie your code to Jetson only, unofficial and potentially unstable (in the sense changing) API

**Comment by bmegli** [comment]
# General recommendation

Access multimedia with FFmpeg or GStreamer (or any other abstraction).
- you don't tie your code with any hardware
- you learn technology applicable across OSes and hardware

**Comment by Kevin4ch** [comment]
thanks a lot, i'm using  ffmeg now.
