### ISSUE TITLE
error:command not found ffmpeg 

### ISSUE THREAD

**Issue by lkw052715** [Keylost/jetson-ffmpeg#18]
After completing the second step, I used ffmpeg and got an error:command not found ffmpeg

**Comment by TobiasKWF** [comment]
These that you are not installed it in the path ...

try make install and then ffmpeg then it should be in the path and run

**Comment by lkw052715** [comment]
Thank you for your prompt reply!
But I want to use python pipe to call ffmpeg how do I do it or can we use our ffmpeg in any folder under the terminal like the official version of ffmpeg, looking forward to your reply!

**Comment by Keylost** [comment]
> Thank you for your prompt reply! But I want to use python pipe to call ffmpeg how do I do it or can we use our ffmpeg in any folder under the terminal like the official version of ffmpeg, looking forward to your reply!
What TobiasKWF wrote was correct. You had to install ffmpeg with "sudo make install" to use this build without specifying full paths.
I added "sudo make install" to the readme just in case :)

**Comment by Keylost** [comment]
> Thank you for your prompt reply! But I want to use python pipe to call ffmpeg how do I do it or can we use our ffmpeg in any folder under the terminal like the official version of ffmpeg, looking forward to your reply!

What TobiasKWF wrote was correct. You had to install ffmpeg with "sudo make install" to use this build without specifying full paths.
I added "sudo make install" to the readme just in case :)
