### ISSUE TITLE
how to check the suitable version of ffmpeg library?

### ISSUE THREAD

**Issue by lmw0320** [Keylost/jetson-ffmpeg#20]
I just git clone the source code, and run the command of  build and install library. I have got the library files. But I'm not clear whether such library are suitable for my ffmpeg? 
My ffmpeg version is 4.2.7,  I did not set any information before build the library. I don't know whether it is necessary?
By the way, after installation of the library, I use the command: ffmpeg -codecs | grep h264, and no h264_nvmpi return。。

**Comment by Keylost** [comment]
> I just git clone the source code, and run the command of build and install library. I have got the library files. But I'm not clear whether such library are suitable for my ffmpeg? My ffmpeg version is 4.2.7, I did not set any information before build the library. I don't know whether it is necessary? By the way, after installation of the library, I use the command: ffmpeg -codecs | grep h264, and no h264_nvmpi return。。

Currently the library is compatible with ffmpeg 4.2, 4.4 and 6.0.
To use the library it is not enough to just install it. You must also patch and build ffmpeg with support for this library. Pay attention to the readme file. There is a rough instruction there. 
Hope this helps)
