### ISSUE TITLE
avcodec_find_encoder_by_name  fail

### ISSUE THREAD

**Issue by lkw052715** [Keylost/jetson-ffmpeg#24]
I was able to use ffmpeg -vcodec h264-nvmpi successfully at the command line, but the avcodec_find_encoder_by_name (h264-nvmpi) function failed.

**Comment by nxsf8023** [comment]
me too do u solve it ?

**Comment by Keylost** [comment]
> I was able to use ffmpeg -vcodec h264-nvmpi successfully at the command line, but the avcodec_find_encoder_by_name (h264-nvmpi) function failed.

If you look closely at the readme, you'll see that the codec name is h264_nvmpi.
You should use avcodec_find_decoder_by_name("h264_nvmpi"), not avcodec_find_decoder_by_name("h264-nvmpi").
Hope this helps.
