### ISSUE TITLE
Encoder output packets are all marked as key frames?

### ISSUE THREAD

**Issue by SeeRich** [Keylost/jetson-ffmpeg#26]
I think I ran into this issue when trying to post process videos created using this encoder. I was trying to use libavformat fast seeking functionality via av_seek_frame and noticed that it kept returning the wrong frames (ie not actual keyframes).

https://github.com/Keylost/jetson-ffmpeg/blob/0d1ccc28687c0fa66dafa2a55fd74fef72037a40/src/nvmpi_enc.cpp#L92

should the above code pull the key frame flag from the buffer metadata? Like in the example code below?

https://github.com/neggles/jetson-multimedia-api/blob/229e15b556fc1ee8c3922bbd5ae27449e346b4c0/samples/01_video_encode/video_encode_main.cpp#L312

**Comment by Keylost** [comment]
You are absolutely right. Thank you. Fixed)
