### ISSUE TITLE
ffmpeg 6.0 on Jetson TX2 NX

### ISSUE THREAD

**Issue by tmaoz** [Keylost/jetson-ffmpeg#4]
Hey,

I previously used jocover's original work with ffmpeg 4 on the TX2 NX and it worked just fine.
However, I wish to move to ffmpeg 6.0 and trying your updated code but getting some errors (it DOES work like a charm on my Orin Dev Kit).

When I run ffmpeg using nvmpi as the input codec, ffmpeg simply gets stuck and there's no debug output to indicate why. I can't even kill ffmpeg (-9 or -15). I do see an endless stream of smmu power errors in dmesg and the only thing I can do is reboot the TX2 NX:

```
[25739.698249] __arm_smmu_context_fault: 193298 callbacks suppressed
[25739.698258] arm-smmu 12000000.iommu: Unhandled context fault: iova=0xb34ca600, fsynr=0x200001, cb=13, sid=6(0x6 - NVDEC), pgd=0, pud=0, pmd=0, pte=0
```

Any idea what is going on? Can your code actually work on the TX2 NX or does it use Orin features that are not available or have been changed from the TX2 NX?

Thanks!

**Comment by Keylost** [comment]
Hi!
The library in this repository should be backward compatible with the old API. Unfortunately I don't have a TX2 NX module to try and reproduce the problem.
Can you use a debugger and provide details of which particular call inside nvmpi is hanging, as well as the complete call stack?
What ffmpeg command are you using?

**Comment by Keylost** [comment]
What version of L4T are you using? Is it the latest version available?

**Comment by tmaoz** [comment]
Hey, so because of some constraints, I'm not using the nvidia Ubuntu but rather a community maintained OS for the TX2 NX boxes.
After digging deeper it turns out they are basing on Ubuntu 22.04 with components from JetPack 4.6.1 while the nvidia Ubuntu for the TX2 NX is based on 18.04.
It turns out to be a GBLIC version incompatibility that causes other issues with various lib incompatibilities.
After much digging I was able to get something running in a container that was based on the `nvidia nvcr.io/nvidia/l4t-ml:r32.7.1-py3` image with manually installed newer versions of libc6, libc-bin, libcrypt, libstdc++ and locales-all...

The manually installs libs break the image's APT system and the entire dependency tree but ffmpeg finally works 🤷‍♂️
